groups:
- name: database_alerts
  rules:
  # PostgreSQL 监控告警
  - alert: PostgreSQLHighConnections
    expr: sum(pg_stat_activity_count) > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "PostgreSQL high connection count"
      description: "PostgreSQL instance has more than 100 connections for 5 minutes"

  - alert: PostgreSQLSlowQueries
    expr: rate(pg_stat_statements_mean_exec_time[5m]) > 1000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "PostgreSQL slow queries detected"
      description: "PostgreSQL has slow queries with average execution time > 1000ms"

  # MongoDB 监控告警
  - alert: MongoDBHighConnections
    expr: mongodb_connections{state="current"} > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB high connection count"
      description: "MongoDB has {{ $value }} connections which is high"

  - alert: MongoDBReplicationLag
    expr: mongodb_mongod_replset_member_optime_date{state="SECONDARY"} - on(set) group_left mongodb_mongod_replset_member_optime_date{state="PRIMARY"} > 10
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "MongoDB replication lag"
      description: "MongoDB replication lag is more than 10 seconds for 5 minutes"

  - alert: MongoDBHighMemoryUsage
    expr: mongodb_memory{type="resident"} / 1024 / 1024 > 1000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB high memory usage"
      description: "MongoDB is using {{ $value }}MB of resident memory"

  # Redis 监控告警
  - alert: RedisMemoryHigh
    expr: redis_memory_used_bytes / redis_config_maxmemory * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Redis memory usage high"
      description: "Redis is using more than 80% of its available memory for 5 minutes"

  - alert: RedisHighConnections
    expr: redis_connected_clients > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Redis high connection count"
      description: "Redis has {{ $value }} client connections which is high"

  - alert: RedisSlowLog
    expr: rate(redis_slowlog_length[5m]) > 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Redis slow queries detected"
      description: "Redis slow log is growing, indicating slow queries"

  # 系统资源监控告警
  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is above 80% for 5 minutes on {{ $labels.instance }}"

  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage detected"
      description: "Memory usage is above 85% for 5 minutes on {{ $labels.instance }}"

  - alert: DiskSpaceHigh
    expr: (node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"}) / node_filesystem_size_bytes{fstype!="tmpfs"} * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High disk usage detected"
      description: "Disk usage is above 85% for 5 minutes on {{ $labels.instance }} filesystem {{ $labels.mountpoint }}"

  # 服务可用性监控
  - alert: MonitoringExporterDown
    expr: up == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Monitoring exporter down"
      description: "{{ $labels.job }} exporter on {{ $labels.instance }} has been down for more than 2 minutes"

  - alert: PrometheusTargetDown
    expr: up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Prometheus target down"
      description: "Prometheus target {{ $labels.job }} on {{ $labels.instance }} is down"
