version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:16
    container_name: ai_platform_postgres
    environment:
      POSTGRES_DB: ai_platform
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai_platform_network

  # Redis 缓存
  redis:
    image: redis:7.2
    container_name: ai_platform_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai_platform_network
  # MinIO 对象存储
  minio:
    image: bitnami/minio:2024.6.4-debian-12-r0
    container_name: ai_platform_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/bitnami/minio/data
    networks:
      - ai_platform_network

  # Dify PostgreSQL 数据库
  dify-postgres:
    image: postgres:16
    container_name: dify_postgres
    environment:
      POSTGRES_DB: dify
      POSTGRES_USER: dify_user
      POSTGRES_PASSWORD: dify_password
    ports:
      - "5433:5432"
    volumes:
      - dify_postgres_data:/var/lib/postgresql/data
    networks:
      - ai_platform_network

  # Dify Redis 缓存
  dify-redis:
    image: redis:7.2
    container_name: dify_redis
    ports:
      - "6380:6379"
    volumes:
      - dify_redis_data:/data
    networks:
      - ai_platform_network
  # Dify Weaviate 向量数据库
  dify-weaviate:
    image: semitechnologies/weaviate:1.24.4
    container_name: dify_weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: text2vec-openai
      CLUSTER_HOSTNAME: 'node1'
    ports:
      - "8081:8080"
    volumes:
      - dify_weaviate_data:/var/lib/weaviate
    networks:
      - ai_platform_network

volumes:
  postgres_data:
  redis_data:
  minio_data:
  dify_postgres_data:
  dify_redis_data:
  dify_weaviate_data:

networks:
  ai_platform_network:
    external: true
