global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

rule_files:
  - "rules/database_alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['localhost:9216']
        labels:
          instance: 'mongodb_server'

  - job_name: 'postgresql'
    static_configs:
      - targets: ['localhost:9187']
        labels:
          instance: 'postgresql_server'

  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']
        labels:
          instance: 'redis_server'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          instance: 'linux_server'

  - job_name: 'weaviate'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8088']
        labels:
          instance: 'vector_db'

  - job_name: 'kafka'
    static_configs:
      - targets: ['localhost:9308']
        labels:
          instance: 'message_queue'

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['localhost:9093']
