# Generated by Django 4.2.7 on 2025-05-28 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="数据源名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("database", "数据库"),
                            ("file", "文件"),
                            ("api", "API"),
                            ("stream", "流数据"),
                        ],
                        max_length=50,
                        verbose_name="数据源类型",
                    ),
                ),
                ("connection_info", models.JSONField(verbose_name="连接信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("tags", models.JSONField(default=list, verbose_name="标签")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据源",
                "verbose_name_plural": "数据源",
                "db_table": "data_sources",
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="数据集名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "file",
                    models.FileField(upload_to="datasets/", verbose_name="数据文件"),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("json", "JSON"),
                            ("parquet", "Parquet"),
                            ("excel", "Excel"),
                            ("txt", "Text"),
                        ],
                        max_length=50,
                        verbose_name="数据格式",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "size_bytes",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "row_count",
                    models.IntegerField(blank=True, null=True, verbose_name="行数"),
                ),
                (
                    "schema_info",
                    models.JSONField(default=dict, verbose_name="数据结构信息"),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="元数据")),
                ("tags", models.JSONField(default=list, verbose_name="标签")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "version",
                    models.CharField(default="1.0", max_length=50, verbose_name="版本"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据集",
                "verbose_name_plural": "数据集",
                "db_table": "datasets",
            },
        ),
        migrations.CreateModel(
            name="DataProcessingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("etl", "ETL处理"),
                            ("clean", "数据清洗"),
                            ("transform", "数据转换"),
                            ("analysis", "数据分析"),
                        ],
                        max_length=50,
                        verbose_name="任务类型",
                    ),
                ),
                ("configuration", models.JSONField(verbose_name="任务配置")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "status_message",
                    models.TextField(blank=True, verbose_name="状态信息"),
                ),
                (
                    "result_data",
                    models.JSONField(default=dict, verbose_name="结果数据"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "source_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_tasks",
                        to="data_platform.dataset",
                        verbose_name="源数据集",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据处理任务",
                "verbose_name_plural": "数据处理任务",
                "db_table": "data_processing_tasks",
            },
        ),
    ]
