version: '3.8'

services:
  mongodb:
    image: mongo:6.0  # 现在可以使用本地镜像
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=changeThisToSecurePassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - ai-platform-network

volumes:
  mongodb_data:
    driver: local

networks:
  ai-platform-network:
    driver: bridge
