# Generated by Django 4.2.7 on 2025-05-28 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Algorithm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="算法名称")),
                ("description", models.TextField(verbose_name="算法描述")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("classification", "分类"),
                            ("regression", "回归"),
                            ("clustering", "聚类"),
                            ("deep_learning", "深度学习"),
                            ("nlp", "自然语言处理"),
                            ("computer_vision", "计算机视觉"),
                            ("recommendation", "推荐系统"),
                            ("time_series", "时间序列"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="算法分类",
                    ),
                ),
                ("framework", models.CharField(max_length=50, verbose_name="算法框架")),
                ("code_template", models.TextField(verbose_name="代码模板")),
                (
                    "default_parameters",
                    models.JSONField(default=dict, verbose_name="默认参数"),
                ),
                (
                    "author",
                    models.CharField(blank=True, max_length=255, verbose_name="作者"),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", max_length=50, verbose_name="版本"
                    ),
                ),
                (
                    "documentation",
                    models.TextField(blank=True, verbose_name="文档说明"),
                ),
                (
                    "is_builtin",
                    models.BooleanField(default=True, verbose_name="是否内置"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "算法模板",
                "verbose_name_plural": "算法模板",
                "db_table": "algorithms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlgorithmProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, verbose_name="项目描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("tensorflow", "TensorFlow"),
                            ("pytorch", "PyTorch"),
                            ("scikit-learn", "Scikit-learn"),
                            ("xgboost", "XGBoost"),
                            ("other", "其他"),
                        ],
                        default="tensorflow",
                        max_length=50,
                        verbose_name="算法框架",
                    ),
                ),
                (
                    "environment_config",
                    models.JSONField(blank=True, default=dict, verbose_name="环境配置"),
                ),
                ("git_repository", models.URLField(blank=True, verbose_name="Git仓库")),
            ],
            options={
                "verbose_name": "算法项目",
                "verbose_name_plural": "算法项目",
                "db_table": "algorithm_projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="实验名称")),
                ("description", models.TextField(blank=True, verbose_name="实验描述")),
                (
                    "algorithm_type",
                    models.CharField(
                        choices=[
                            ("classification", "分类"),
                            ("regression", "回归"),
                            ("clustering", "聚类"),
                            ("deep_learning", "深度学习"),
                            ("nlp", "自然语言处理"),
                            ("computer_vision", "计算机视觉"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="算法类型",
                    ),
                ),
                (
                    "hyperparameters",
                    models.JSONField(blank=True, default=dict, verbose_name="超参数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "已创建"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("stopped", "已停止"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "算法实验",
                "verbose_name_plural": "算法实验",
                "db_table": "algorithm_experiments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExperimentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="运行ID"
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
                (
                    "parameters",
                    models.JSONField(blank=True, default=dict, verbose_name="运行参数"),
                ),
                (
                    "metrics",
                    models.JSONField(blank=True, default=dict, verbose_name="评估指标"),
                ),
                (
                    "artifacts",
                    models.JSONField(blank=True, default=dict, verbose_name="产出文件"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "排队中"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("killed", "已终止"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="运行时长"
                    ),
                ),
                (
                    "resource_usage",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="资源使用情况"
                    ),
                ),
                ("logs", models.TextField(blank=True, verbose_name="运行日志")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="algorithm_platform.experiment",
                        verbose_name="所属实验",
                    ),
                ),
            ],
            options={
                "verbose_name": "实验运行记录",
                "verbose_name_plural": "实验运行记录",
                "db_table": "algorithm_experiment_runs",
                "ordering": ["-created_at"],
            },
        ),
    ]
