# Generated by Django 4.2.7 on 2025-05-28 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("algorithm_platform", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data_platform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiment",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="experiment",
            name="dataset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data_platform.dataset",
                verbose_name="训练数据集",
            ),
        ),
        migrations.AddField(
            model_name="experiment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiments",
                to="algorithm_platform.algorithmproject",
                verbose_name="所属项目",
            ),
        ),
        migrations.AddField(
            model_name="algorithmproject",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="algorithmproject",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.organization",
                verbose_name="所属组织",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="experimentrun",
            unique_together={("experiment", "version")},
        ),
    ]
