global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Triton Inference Server 监控
  - job_name: 'triton-server'
    static_configs:
      - targets: ['triton-server:8002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Django 后端监控 (如果启用了 metrics)
  - job_name: 'django-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # 可选: GPU 监控 (需要 DCGM Exporter)
  - job_name: 'dcgm-exporter'
    static_configs:
      - targets: ['dcgm-exporter:9400']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # PostgreSQL 监控 (可选)
  # - job_name: 'postgres-exporter'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Redis 监控 (可选)
  # - job_name: 'redis-exporter'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
