# Generated by Django 4.2.7 on 2025-05-28 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("algorithm_platform", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="模型名称")),
                ("description", models.TextField(blank=True, verbose_name="模型描述")),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("classification", "分类模型"),
                            ("regression", "回归模型"),
                            ("clustering", "聚类模型"),
                            ("deep_learning", "深度学习模型"),
                            ("nlp", "NLP模型"),
                            ("computer_vision", "计算机视觉模型"),
                            ("recommendation", "推荐模型"),
                            ("time_series", "时间序列模型"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="模型类型",
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("tensorflow", "TensorFlow"),
                            ("pytorch", "PyTorch"),
                            ("scikit-learn", "Scikit-learn"),
                            ("xgboost", "XGBoost"),
                            ("lightgbm", "LightGBM"),
                            ("onnx", "ONNX"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="模型框架",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "训练中"),
                            ("trained", "训练完成"),
                            ("validated", "验证完成"),
                            ("registered", "已注册"),
                            ("deployed", "已部署"),
                            ("archived", "已归档"),
                        ],
                        default="training",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.organization",
                        verbose_name="所属组织",
                    ),
                ),
                (
                    "source_experiment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="algorithm_platform.experiment",
                        verbose_name="来源实验",
                    ),
                ),
            ],
            options={
                "verbose_name": "机器学习模型",
                "verbose_name_plural": "机器学习模型",
                "db_table": "ml_models",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="端点名称")),
                ("description", models.TextField(blank=True, verbose_name="端点描述")),
                ("endpoint_url", models.URLField(blank=True, verbose_name="端点URL")),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API密钥"
                    ),
                ),
                (
                    "deployment_config",
                    models.JSONField(blank=True, default=dict, verbose_name="部署配置"),
                ),
                (
                    "resource_requirements",
                    models.JSONField(blank=True, default=dict, verbose_name="资源需求"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "创建中"),
                            ("active", "运行中"),
                            ("updating", "更新中"),
                            ("inactive", "已停止"),
                            ("failed", "失败"),
                            ("deleted", "已删除"),
                        ],
                        default="creating",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "health_check_url",
                    models.URLField(blank=True, verbose_name="健康检查URL"),
                ),
                (
                    "last_health_check",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后健康检查时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "deployed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="部署时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "模型端点",
                "verbose_name_plural": "模型端点",
                "db_table": "model_endpoints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50, verbose_name="版本号")),
                ("description", models.TextField(blank=True, verbose_name="版本描述")),
                (
                    "model_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="models/",
                        verbose_name="模型文件",
                    ),
                ),
                (
                    "model_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "model_format",
                    models.CharField(
                        choices=[
                            ("pkl", "Pickle"),
                            ("h5", "HDF5"),
                            ("pb", "TensorFlow SavedModel"),
                            ("pth", "PyTorch"),
                            ("onnx", "ONNX"),
                            ("joblib", "Joblib"),
                            ("other", "其他"),
                        ],
                        default="pkl",
                        max_length=50,
                        verbose_name="模型格式",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(blank=True, default=dict, verbose_name="性能指标"),
                ),
                (
                    "hyperparameters",
                    models.JSONField(blank=True, default=dict, verbose_name="超参数"),
                ),
                (
                    "training_config",
                    models.JSONField(blank=True, default=dict, verbose_name="训练配置"),
                ),
                (
                    "is_latest",
                    models.BooleanField(default=True, verbose_name="是否最新版本"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="model_platform.mlmodel",
                        verbose_name="所属模型",
                    ),
                ),
            ],
            options={
                "verbose_name": "模型版本",
                "verbose_name_plural": "模型版本",
                "db_table": "model_versions",
                "ordering": ["-created_at"],
                "unique_together": {("model", "version")},
            },
        ),
        migrations.CreateModel(
            name="ModelPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="请求ID"
                    ),
                ),
                ("input_data", models.JSONField(default=dict, verbose_name="输入数据")),
                (
                    "output_data",
                    models.JSONField(default=dict, verbose_name="输出数据"),
                ),
                (
                    "prediction_result",
                    models.JSONField(default=dict, verbose_name="预测结果"),
                ),
                (
                    "confidence_score",
                    models.FloatField(blank=True, null=True, verbose_name="置信度"),
                ),
                (
                    "latency_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="延迟(毫秒)"
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="处理时间(毫秒)"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="用户代理"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("error", "错误"),
                            ("timeout", "超时"),
                        ],
                        default="success",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="model_platform.modelendpoint",
                        verbose_name="模型端点",
                    ),
                ),
            ],
            options={
                "verbose_name": "模型预测记录",
                "verbose_name_plural": "模型预测记录",
                "db_table": "model_predictions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="modelendpoint",
            name="model_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="endpoints",
                to="model_platform.modelversion",
                verbose_name="模型版本",
            ),
        ),
        migrations.CreateModel(
            name="ModelRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registry_name",
                    models.CharField(max_length=255, verbose_name="注册名称"),
                ),
                (
                    "registry_tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                (
                    "model_schema",
                    models.JSONField(blank=True, default=dict, verbose_name="模型架构"),
                ),
                (
                    "input_schema",
                    models.JSONField(blank=True, default=dict, verbose_name="输入架构"),
                ),
                (
                    "output_schema",
                    models.JSONField(blank=True, default=dict, verbose_name="输出架构"),
                ),
                (
                    "validation_dataset",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="验证数据集"
                    ),
                ),
                (
                    "validation_metrics",
                    models.JSONField(blank=True, default=dict, verbose_name="验证指标"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="是否审批通过"),
                ),
                (
                    "approval_notes",
                    models.TextField(blank=True, verbose_name="审批备注"),
                ),
                (
                    "registered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registry_entries",
                        to="model_platform.mlmodel",
                        verbose_name="模型",
                    ),
                ),
            ],
            options={
                "verbose_name": "模型注册表",
                "verbose_name_plural": "模型注册表",
                "db_table": "model_registry",
                "ordering": ["-registered_at"],
                "unique_together": {("model", "registry_name")},
            },
        ),
    ]
